version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network 

  gradio-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5155:5155"
    environment:
      - FOR_CONTAINER=true
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge